# Tests del módulo github.com/devpablocristo/platform/features/crud/paths/go.
# Build: context = padre de `platform`.
FROM golang:1.26-bookworm
WORKDIR /repo/platform/features/crud/paths/go

COPY platform/features/crud/paths/go/go.mod ./
COPY platform/features/crud/paths/go/ ./

RUN go test ./...

CMD ["go", "version"]
