version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/authn/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/browser/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/http/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/ai/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/http/python"
    schedule:
      interval: "weekly"
