// Package lifecycle provides a domain-agnostic API for the CRUDAR cycle:
// Create-Read-Update-Delete-Archive-Restore (and bulk archive, retention,
// audit, policies).
//
// Design constraints (see platform/docs/migration plan — Invariantes de
// agnosticidad):
//
//   - ResourceType and Action are opaque strings. This package does not know
//     any product entity (no "customer", "quote", "invoice", etc.). The
//     consumer (e.g. pymes) supplies the vocabulary.
//   - Audit schema is polymorphic via resource_type + resource_id. No foreign
//     keys to domain tables.
//   - Policies are infrastructure: this package defines the mechanism
//     (interface, validator), the consumer registers concrete policies.
//   - SQL column names are parametrizable via SoftDeleterConfig.
//   - Identity (actor, tenant) is opaque strings; this package does not assume
//     any auth provider or UUID-based tenant format.
package lifecycle

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Action is the action recorded in audit. Conventional values used by this
// package: ActionArchive, ActionRestore, ActionHardDelete. Callers can extend
// with their own values (the field is a plain string).
type Action string

const (
	ActionArchive    Action = "archive"
	ActionRestore    Action = "restore"
	ActionHardDelete Action = "hard_delete"
)

// ArchiveRequest captures the input to SoftDelete and BulkArchive.
//
// ResourceType is opaque (e.g. "customer", "quote" — chosen by the caller).
// TenantID is the owner of the resource (org_id, workspace_id, etc.). It is an
// opaque string because not every product uses UUID tenants.
// Actor is the identity performing the action (subject_id, email, service
// account, agent ID — opaque to this package).
// Reason is optional and always logged when present.
// BatchID groups bulk operations under a single correlation ID.
type ArchiveRequest struct {
	ResourceType string
	ResourceID   uuid.UUID
	TenantID     string
	Actor        string
	Reason       string
	BatchID      *uuid.UUID
}

// RestoreRequest captures the input to Restore.
type RestoreRequest struct {
	ResourceType string
	ResourceID   uuid.UUID
	TenantID     string
	Actor        string
	Reason       string
}

// HardDeleteRequest captures the input to HardDelete.
//
// MustBeArchived: when true, HardDelete refuses to delete a resource that has
// not been archived first (forces a soft → hard transition). Callers that want
// direct hard deletes can set this to false.
type HardDeleteRequest struct {
	ResourceType   string
	ResourceID     uuid.UUID
	TenantID       string
	Actor          string
	Reason         string
	MustBeArchived bool
}

// ArchiveAudit is the append-only audit record produced by every action.
// The hash chain (PrevHash → Hash) is computed by the implementation; see
// platform/kernels/activity/go for the canonical hash-chain audit log this
// package integrates with by default.
type ArchiveAudit struct {
	ID               uuid.UUID
	TenantID         string
	ResourceType     string
	ResourceID       uuid.UUID
	Action           Action
	OccurredAt       time.Time
	Actor            string
	Reason           *string
	BatchID          *uuid.UUID
	RetentionExpires *time.Time
}

// ArchivedQuery filters ListArchived results.
type ArchivedQuery struct {
	TenantID     string
	ResourceType string // optional; empty = all
	Since        *time.Time
	Until        *time.Time
	Actor        string // optional
	BatchID      *uuid.UUID
	Limit        int // 0 = caller default
}

// BulkArchiveResult reports per-ID outcome of BulkArchive.
type BulkArchiveResult struct {
	ResourceID uuid.UUID
	Err        error // nil on success
}

// AuditPort is the dependency this package needs to persist audit records.
// Consumers typically wire platform/kernels/activity/go but any
// implementation that respects the contract is acceptable.
type AuditPort interface {
	Append(ctx context.Context, entry ArchiveAudit) error
}

// RepositoryPort is the dependency this package needs to persist the soft
// archive on the resource's own table. Implementations are typically
// generated by NewSoftDeleter (see repository_helper.go) or hand-written by
// the consumer for tables with non-standard schemas.
//
// The implementation must scope every operation to TenantID for multi-tenant
// safety.
type RepositoryPort interface {
	SoftDelete(ctx context.Context, tenantID string, resourceID uuid.UUID, at time.Time) error
	Restore(ctx context.Context, tenantID string, resourceID uuid.UUID) error
	HardDelete(ctx context.Context, tenantID string, resourceID uuid.UUID) error
	IsArchived(ctx context.Context, tenantID string, resourceID uuid.UUID) (bool, error)
}

// Clock is used to inject time for tests. Default: time.Now().UTC.
type Clock func() time.Time
